//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class InfoControl_POS_PurchaseOrders {
    
    /// <summary>
    /// cboPurchaseOrderStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList cboPurchaseOrderStatus;
    
    /// <summary>
    /// cboPageSize control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList cboPageSize;
    
    /// <summary>
    /// btnFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnFilter;
    
    /// <summary>
    /// grdPurchaseOrders control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.GridView grdPurchaseOrders;
    
    /// <summary>
    /// odsPurchaseOrderStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::InfoControl.Web.UI.WebControls.BusinessManagerDataSource odsPurchaseOrderStatus;
    
    /// <summary>
    /// odsPurchaseOrders control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::InfoControl.Web.UI.WebControls.BusinessManagerDataSource odsPurchaseOrders;
}
