//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exception", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver pelo menos uma linha com dados do produto.
        /// </summary>
        internal static string AddProductInList {
            get {
                return ResourceManager.GetString("AddProductInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deste administrador já está cadastrado no nosso sistema !.
        /// </summary>
        internal static string AdministratorCPFAlreadyExist {
            get {
                return ResourceManager.GetString("AdministratorCPFAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail para este Administrador já está cadastrado no nosso sistema !.
        /// </summary>
        internal static string AdministratorEmailAlreadyExist {
            get {
                return ResourceManager.GetString("AdministratorEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor do contrato deve ser preenchido.
        /// </summary>
        internal static string AssociatedContractValueIsEmpty {
            get {
                return ResourceManager.GetString("AssociatedContractValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta empresa não possui modelo de proposta!.
        /// </summary>
        internal static string BudgetDocumentTemplateIsNull {
            get {
                return ResourceManager.GetString("BudgetDocumentTemplateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa empresa não possui modelo de Solicitação de Orçamento.
        /// </summary>
        internal static string BudgetRequestTemplateIsNull {
            get {
                return ResourceManager.GetString("BudgetRequestTemplateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CNPJ já está cadastrado no nosso sistema!.
        /// </summary>
        internal static string CNPJAlreadyExist {
            get {
                return ResourceManager.GetString("CNPJAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A empresa já se encontra cadastrada no sistema !.
        /// </summary>
        internal static string CompanyAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Contrato Foi Gerado com o status Dependente pois o cliente não possui limite de crédito suficiente!.
        /// </summary>
        internal static string ContractGeneratedAsdepend {
            get {
                return ResourceManager.GetString("ContractGeneratedAsdepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Status do contrato não pode ser Aprovado pois o Cliente não possui limite de crédito suficiente!.
        /// </summary>
        internal static string CustomerCreditLimitInvalid {
            get {
                return ResourceManager.GetString("CustomerCreditLimitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data selecionada deve ser menor que a data corrente .
        /// </summary>
        internal static string DateBiggerThanCurrentDate {
            get {
                return ResourceManager.GetString("DateBiggerThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento do contrato deve ser preenchida.
        /// </summary>
        internal static string DateExpiredAssociatedContractIsEmpty {
            get {
                return ResourceManager.GetString("DateExpiredAssociatedContractIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro não pode ser apagado pois há outros registros associados!.
        /// </summary>
        internal static string DeletingRegisterWithForeignKey {
            get {
                return ResourceManager.GetString("DeletingRegisterWithForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este código já está cadastrado.
        /// </summary>
        internal static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro; o arquivo não se encontra nos padrões de importação..
        /// </summary>
        internal static string errorOnImportDocument {
            get {
                return ResourceManager.GetString("errorOnImportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não concluída, e-mail já está cadastrado no sistema.
        /// </summary>
        internal static string ExistentMail {
            get {
                return ResourceManager.GetString("ExistentMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem outras categorias associadas à esta categoria!.
        /// </summary>
        internal static string ExistsChildCategories {
            get {
                return ResourceManager.GetString("ExistsChildCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem produtos incluídos nessa categoria!.
        /// </summary>
        internal static string ExistsProductInCategory {
            get {
                return ResourceManager.GetString("ExistsProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário selecionado já foi adicionado.
        /// </summary>
        internal static string ExistUser {
            get {
                return ResourceManager.GetString("ExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário inserir ao menos um produto..
        /// </summary>
        internal static string InsertProduct {
            get {
                return ResourceManager.GetString("InsertProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário inserir pelo menos um serviço.
        /// </summary>
        internal static string InsertService {
            get {
                return ResourceManager.GetString("InsertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um nome para o plano de contas.
        /// </summary>
        internal static string InvalidAccountPlanName {
            get {
                return ResourceManager.GetString("InvalidAccountPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A exportação para este banco ainda não foi implementada!.
        /// </summary>
        internal static string InvalidBank {
            get {
                return ResourceManager.GetString("InvalidBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da conta à pagar deve ser o mesmo valor do somatorio das parcelas.
        /// </summary>
        internal static string InvalidBillAmount {
            get {
                return ResourceManager.GetString("InvalidBillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Razão social deve ser preenchido!.
        /// </summary>
        internal static string InvalidCompanyName {
            get {
                return ResourceManager.GetString("InvalidCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor do contrato deve ser preenchido!.
        /// </summary>
        internal static string InvalidContractAssociatedAmount {
            get {
                return ResourceManager.GetString("InvalidContractAssociatedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento do contrato deve ser preenchida!.
        /// </summary>
        internal static string InvalidContractAssociatedDueDate {
            get {
                return ResourceManager.GetString("InvalidContractAssociatedDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um nome para o centro de custo..
        /// </summary>
        internal static string InvalidCostCenterName {
            get {
                return ResourceManager.GetString("InvalidCostCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data selecionada não é válida.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor selecionado para o desconto não é válido.
        /// </summary>
        internal static string InvalidDiscountValue {
            get {
                return ResourceManager.GetString("InvalidDiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do arquivo selecionado não é válido.
        /// </summary>
        internal static string InvalidFormatFile {
            get {
                return ResourceManager.GetString("InvalidFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não concluída, senha inválida..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade deve ser maior que 0.
        /// </summary>
        internal static string InvalidProductQuantity {
            get {
                return ResourceManager.GetString("InvalidProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número informado para a nota fiscal já existe na base de dados.
        /// </summary>
        internal static string InvalidReceiptNumber {
            get {
                return ResourceManager.GetString("InvalidReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estoque não pode ser negativo..
        /// </summary>
        internal static string InvalidStockQuantity {
            get {
                return ResourceManager.GetString("InvalidStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida! A senha deve ter pelo menos 6 caracteres composto por numeros, letras e simbolos!.
        /// </summary>
        internal static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF não encontra - se cadastrado..
        /// </summary>
        internal static string nonExistentCPF {
            get {
                return ResourceManager.GetString("nonExistentCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário adicionar ao menos uma parcela!.
        /// </summary>
        internal static string NonExistentParcel {
            get {
                return ResourceManager.GetString("NonExistentParcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse produto ainda não foi cadastrado.
        /// </summary>
        internal static string nonexistentProduct {
            get {
                return ResourceManager.GetString("nonexistentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto/serviço selecionado não existe.
        /// </summary>
        internal static string NonExistentProductOrService {
            get {
                return ResourceManager.GetString("NonExistentProductOrService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe venda associada ao nº fornecido.
        /// </summary>
        internal static string nonexistentReceiptNumber {
            get {
                return ResourceManager.GetString("nonexistentReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda inexistente..
        /// </summary>
        internal static string nonExistentSale {
            get {
                return ResourceManager.GetString("nonExistentSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse serviço ainda não foi cadastrado.
        /// </summary>
        internal static string nonexistentService {
            get {
                return ResourceManager.GetString("nonexistentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto não pode ser enviado para o RMA..
        /// </summary>
        internal static string nonSentProductToRMA {
            get {
                return ResourceManager.GetString("nonSentProductToRMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa empresa não tem modelo de ordem de compra!.
        /// </summary>
        internal static string PurchaseDocumentTemplateIsNull {
            get {
                return ResourceManager.GetString("PurchaseDocumentTemplateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma categoria na árvore ao lado..
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe um valor selecionado.
        /// </summary>
        internal static string SelectedValue {
            get {
                return ResourceManager.GetString("SelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar ao menos um produto.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione ao menos um produto ou serviço!.
        /// </summary>
        internal static string ServiceOrderWithoutProductAndService {
            get {
                return ResourceManager.GetString("ServiceOrderWithoutProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hora de início não pode ser maior que a hora de término!.
        /// </summary>
        internal static string StartTimeIsBiggerThanEndTime {
            get {
                return ResourceManager.GetString("StartTimeIsBiggerThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor das parcelas não coincide com o valor da conta.
        /// </summary>
        internal static string SummaryParcelNotEqualDocumentValue {
            get {
                return ResourceManager.GetString("SummaryParcelNotEqualDocumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa empresa não possui modelo de Autorização de Fornecimento.
        /// </summary>
        internal static string SupplyAuthorizationTemplateIsNull {
            get {
                return ResourceManager.GetString("SupplyAuthorizationTemplateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neste intervalo de tempo o funcionário não está disponivel!.
        /// </summary>
        internal static string unavailableEmployee {
            get {
                return ResourceManager.GetString("unavailableEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um plano de contas.
        /// </summary>
        internal static string UnselectedAccountPlan {
            get {
                return ResourceManager.GetString("UnselectedAccountPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um centro de custo.
        /// </summary>
        internal static string UnselectedCostCenter {
            get {
                return ResourceManager.GetString("UnselectedCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um cliente.
        /// </summary>
        internal static string UnselectedCustomer {
            get {
                return ResourceManager.GetString("UnselectedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um empregado.
        /// </summary>
        internal static string UnselectedEmployee {
            get {
                return ResourceManager.GetString("UnselectedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo do evento.
        /// </summary>
        internal static string UnselectedEventType {
            get {
                return ResourceManager.GetString("UnselectedEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um item.
        /// </summary>
        internal static string UnselectedItem {
            get {
                return ResourceManager.GetString("UnselectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um advogado.
        /// </summary>
        internal static string UnselectedLawyer {
            get {
                return ResourceManager.GetString("UnselectedLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um produto ou serviço.
        /// </summary>
        internal static string UnselectedProductOrService {
            get {
                return ResourceManager.GetString("UnselectedProductOrService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário criado com sucesso !.
        /// </summary>
        internal static string UserCreatedIsValid {
            get {
                return ResourceManager.GetString("UserCreatedIsValid", resourceCulture);
            }
        }
    }
}
