//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoControl.Web.UI.WebControls.Boleto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoControl.Web.UI.WebControls.Boleto.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;150&quot;&gt;
        ///            &lt;img src=&quot;[=sImgBancoLogoTipo=]&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;2&quot;&gt;
        ///            &lt;img src=&quot;[=sImgBarra=]&quot; height=&quot;22&quot; width=&quot;2&quot; border=&quot;0&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; align=&quot;center&quot; width=&quot;75&quot;&gt;
        ///            &lt;span id=&quot;nb1&quot; class=&quot;nbanco&quot;&gt;[=BancoCodigoCompleto=]&lt;/span&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;2&quot;&gt;
        ///            &lt;img height=&quot;22&quot; src=&quot;[=sImgBarra=]&quot; width=&quot;2&quot; border=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComprovanteEntrega {
            get {
                return ResourceManager.GetString("ComprovanteEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table bordercolor=&quot;#000000&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;1&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td valign=&quot;top&quot; colspan=&quot;5&quot;&gt;
        ///            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td class=&quot;ct&quot;&gt;
        ///                        &amp;nbsp;Local de Pagamento&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td class=&quot;cp&quot;&gt;
        ///                        &amp;nbsp;[=LocalPagamento=]&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/table&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Corpo {
            get {
                return ResourceManager.GetString("Corpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div align=center&gt;&lt;img src=&quot;[=sImgCorte=]&quot;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string LinhaCorte {
            get {
                return ResourceManager.GetString("LinhaCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;150&quot;&gt;
        ///            &lt;img src=&quot;[=sImgBancoLogoTipo=]&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;2&quot;&gt;
        ///            &lt;img height=&quot;22&quot; src=&quot;[=sImgBarra=]&quot; width=&quot;2&quot; border=&quot;0&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; align=&quot;center&quot; width=&quot;75&quot; class=&quot;nbanco&quot;&gt;
        ///            &lt;span id=&quot;nb3&quot;&gt;[=BancoCodigoCompleto=]&lt;/span&gt;
        ///            &amp;nbsp;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;1&quot;&gt;
        ///            &lt;img height=&quot;22&quot; src=&quot;[=sImgBarra=] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParteBanco {
            get {
                return ResourceManager.GetString("ParteBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;ct&quot;&gt;
        ///            &amp;nbsp;&lt;/td&gt;
        ///        &lt;td class=&quot;ct&quot; valign=&quot;top&quot; align=&quot;center&quot; width=&quot;150&quot;&gt;
        ///            &amp;nbsp;Autenticação Mecânica&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;br&gt;
        ///            &lt;span id=&quot;CodBarras&quot;&gt;[=CodigoBarras=]&lt;/span&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;cp&quot; valign=&quot;bottom&quot; align=&quot;right&quot;&gt;
        ///            &amp;nbsp;Ficha de Compensação&amp;nbsp;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ParteBancoFim {
            get {
                return ResourceManager.GetString("ParteBancoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;150&quot;&gt;
        ///            &lt;img src=&quot;[=sImgBancoLogoTipo=]&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;2&quot;&gt;
        ///            &lt;img src=&quot;[=sImgBarra=]&quot; height=&quot;22&quot; width=&quot;2&quot; border=&quot;0&quot;&gt;&lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; align=&quot;center&quot; width=&quot;75&quot; class=&quot;nbanco&quot;&gt;
        ///            &lt;span id=&quot;nb2&quot;&gt;[=BancoCodigoCompleto=]&lt;/span&gt;
        ///        &lt;/td&gt;
        ///        &lt;td valign=&quot;bottom&quot; width=&quot;2&quot;&gt;
        ///            &lt;img height=&quot;22&quot; src=&quot;[=sImgBarra=]&quot; width=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboSacado {
            get {
                return ResourceManager.GetString("ReciboSacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;ct&quot;&gt;
        ///            &amp;nbsp;Recebi através do cheque n°
        ///            &lt;br&gt;
        ///            &amp;nbsp;do banco:&lt;br&gt;
        ///            &amp;nbsp;Esta quitação só terá validade após pagamento do cheque pelo Banco sacado.
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;ct&quot; valign=&quot;top&quot; align=&quot;center&quot; width=&quot;150&quot;&gt;
        ///            Autenticação Mecânica&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoFim {
            get {
                return ResourceManager.GetString("ReciboSacadoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ti
        ///{
        ///	font: 9px arial, helvetica, sans-serif;
        ///}
        ///.ct
        ///{
        ///	font: 9px arial narrow;
        ///	color: #000000;
        ///}
        ///.cn
        ///{
        ///	font: 9px arial;
        ///	color: #000000;
        ///}
        ///.cp
        ///{
        ///	font: bold 11px arial;
        ///	color: #000000;
        ///}
        ///.ld
        ///{
        ///	font: bold 11px arial;
        ///	color: #000000;
        ///}
        ///.bc
        ///{
        ///	font: bold 18px arial;
        ///	color: #000000;
        ///}
        ///.lLinhaDigitavel
        ///{
        ///	font: bold 15px arial;
        ///	color: #000000;
        ///}
        ///.SaltoDePagina
        ///{
        ///	page-break-after: always;
        ///}
        ///.nbanco
        ///{
        ///	font: bold 25px arial;
        ///}
        ///.
        /// </summary>
        internal static string Stylesheet {
            get {
                return ResourceManager.GetString("Stylesheet", resourceCulture);
            }
        }
    }
}
