//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a non-autogenerated machine key to store passwords in the encrypted format. Either specify a different passwordFormat, or change the machineKey configuration to use a non-autogenerated decryption key..
        /// </summary>
        internal static string Can_not_use_encrypted_passwords_with_autogen_keys {
            get {
                return ResourceManager.GetString("Can_not_use_encrypted_passwords_with_autogen_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CURRENT_DataManager_KEY.
        /// </summary>
        internal static string CurrentDataManagerKey {
            get {
                return ResourceManager.GetString("CurrentDataManagerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt a one-way hash!.
        /// </summary>
        internal static string Cypher_DecryptHash {
            get {
                return ResourceManager.GetString("Cypher_DecryptHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2B202B746511891C1BAF47F8D25C07F6C39A104696DB51F1.
        /// </summary>
        internal static string Cypher_DefaultKey {
            get {
                return ResourceManager.GetString("Cypher_DefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename is invalid!.
        /// </summary>
        internal static string Cypher_InvalidPath {
            get {
                return ResourceManager.GetString("Cypher_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid cryptographic provider was specified for this method!.
        /// </summary>
        internal static string Cypher_InvalidProvider {
            get {
                return ResourceManager.GetString("Cypher_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No algorithm was specified!.
        /// </summary>
        internal static string Cypher_NoAlgorithm {
            get {
                return ResourceManager.GetString("Cypher_NoAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content was provided!.
        /// </summary>
        internal static string Cypher_NoContent {
            get {
                return ResourceManager.GetString("Cypher_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not exist!.
        /// </summary>
        internal static string Cypher_NoFile {
            get {
                return ResourceManager.GetString("Cypher_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encryption key was provided!.
        /// </summary>
        internal static string Cypher_NoKey {
            get {
                return ResourceManager.GetString("Cypher_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file!.
        /// </summary>
        internal static string Cypher_NotPermissionFileRead {
            get {
                return ResourceManager.GetString("Cypher_NotPermissionFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file!!.
        /// </summary>
        internal static string Cypher_NotPermissionFileWrite {
            get {
                return ResourceManager.GetString("Cypher_NotPermissionFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q+6lZpmZzL+9AcbMDFC9mTFHWR8vfO82KJXbD6d1OlgW1Ly81F+NaOhZ6rQDr6C4lFleOGlzLMvBN5FDxok15+fyF9jjoDl36iR0Ha8r0q9b1nS9We1w994muFo/W8uma6iJRJKc+7yb90cAQZhbGUgZRQ9Ab+GLT3di0g+opZSTsMrptSQxCp+iT4AQJN9pMD1SR7QzwrQiDxvMI8pOZnsvU6mM1XH84qy9/2BzPbyqeyQiYxhr3fXDucjZYXEUEt9+6pJebqO+VaCncTYrN4BU2+ZaN/QNO7oWZHPv37hWehPPfMpWa+lTnovq7KMyF2PNDCamdcA79iPHxGmEmLSjvgznp7xWLq0VARE/Yzhc8AUp/LcX2/Z3pH2hFvNfi+pmxfc1oFESYqEe+ujanYH2xkpzEM/XLdEm4aLzZHF9k42mdksS0DKwgPktoE26JhUmKJt2qP+MEwCMsF/S+5+vft5hQqrzW/L2Jra5GUs0jFO+RIExbxgRiPn6A4gy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cypher_PrivateKey {
            get {
                return ResourceManager.GetString("Cypher_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q+6lZpmZzL+9AcbMDFC9mTFHWR8vfO82KJXbD6d1OlgW1Ly81F+NaOhZ6rQDr6C4lFleOGlzLMvBN5FDxok15+fyF9jjoDl36iR0Ha8r0q9b1nS9We1w994muFo/W8uma6iJRJKc+7yb90cAQZhbGUgZRQ9Ab+GLT3di0g+opZSTsMrptSQxCp+iT4AQJN9pMD1SR7QzwrQiDxvMI8pOZnsvU6mM1XH84qy9/2BzPbyqeyQiYxhr3fXDucjZYXEUEt9+6pJebqO+VaCncTYrN4BU2+ZaN/QNO7oWZHPv37i3fw+M/cfYFhiCnGvtZZka8PZb14iXVyGKRLFsQccSYg==.
        /// </summary>
        internal static string Cypher_PublicKey {
            get {
                return ResourceManager.GetString("Cypher_PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSourceID of &apos;{0}&apos; must be the ID of a control of type IDataSource.  A control with ID &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string DataControl_DataSourceDoesntExist {
            get {
                return ResourceManager.GetString("DataControl_DataSourceDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSourceID of &apos;{0}&apos; must be the ID of a control of type IDataSource.  &apos;{1}&apos; is not an IDataSource..
        /// </summary>
        internal static string DataControl_DataSourceIDMustBeDataControl {
            get {
                return ResourceManager.GetString("DataControl_DataSourceIDMustBeDataControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both DataSource and DataSourceID are defined on &apos;{0}&apos;.  Remove one definition..
        /// </summary>
        internal static string DataControl_MultipleDataSources {
            get {
                return ResourceManager.GetString("DataControl_MultipleDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view that data bound control &apos;{0}&apos; requested could not be found. Check that the DataMember property is valid..
        /// </summary>
        internal static string DataControl_ViewNotFound {
            get {
                return ResourceManager.GetString("DataControl_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O controle  InfoControl.Web.UI.DataUserControl só pode ser utilizado em uma página herdada de InfoControl.Web.UI.DataPage.
        /// </summary>
        internal static string DataUserControl_BadCaller {
            get {
                return ResourceManager.GetString("DataUserControl_BadCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O controle InfoControl.Web.UI.MasterPage só pode ser utilizado em uma página herdada de InfoControl.Web.UI.Page.
        /// </summary>
        internal static string MasterPage_BadCaller {
            get {
                return ResourceManager.GetString("MasterPage_BadCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pageIndex must be greater than or equal to zero..
        /// </summary>
        internal static string PageIndex_bad {
            get {
                return ResourceManager.GetString("PageIndex_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of pageIndex and pageSize cannot exceed the maximum value of System.Int32..
        /// </summary>
        internal static string PageIndex_PageSize_bad {
            get {
                return ResourceManager.GetString("PageIndex_PageSize_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pageSize must be greater than zero..
        /// </summary>
        internal static string PageSize_bad {
            get {
                return ResourceManager.GetString("PageSize_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must not be empty..
        /// </summary>
        internal static string Parameter_can_not_be_empty {
            get {
                return ResourceManager.GetString("Parameter_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        internal static string Parameter_cannot_be_NullOrEmpty {
            get {
                return ResourceManager.GetString("Parameter_cannot_be_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is invalid. .
        /// </summary>
        internal static string Parameter_Invalid {
            get {
                return ResourceManager.GetString("Parameter_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        internal static string Parameter_too_long {
            get {
                return ResourceManager.GetString("Parameter_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permissionRequired.
        /// </summary>
        internal static string PermissionRequiredKey {
            get {
                return ResourceManager.GetString("PermissionRequiredKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section &apos;{0}&apos; dont was configured!.
        /// </summary>
        internal static string Section_dont_was_configured {
            get {
                return ResourceManager.GetString("Section_dont_was_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} in configuration file dont was configured!.
        /// </summary>
        internal static string Section_NoConfigured {
            get {
                return ResourceManager.GetString("Section_NoConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O controle InfoControl.Web.UI.UserControl só pode ser utilizado em uma página herdada de InfoControl.Web.UI.Page.
        /// </summary>
        internal static string UserControl_BadCaller {
            get {
                return ResourceManager.GetString("UserControl_BadCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the User in Page, required configure the HttpModule VivinaRoleProvider.
        /// </summary>
        internal static string VivinaRoleProviderNotConfigured {
            get {
                return ResourceManager.GetString("VivinaRoleProviderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;formats&gt;
        ///  &lt;format name=&quot;A4348&quot;
        ///     PageTopMargin=&quot;12.5&quot;
        ///     PageRightMargin=&quot;7&quot;
        ///     PageBottomMargin=&quot;12.5&quot;
        ///     PageLeftMargin=&quot;7&quot;
        ///     PageHeight=&quot;297&quot;
        ///     PageWidth=&quot;210&quot;
        ///     LabelHeight=&quot;17&quot;
        ///     LabelWidth=&quot;31&quot;
        ///     LabelRightMargin=&quot;2&quot;
        ///     LabelBottomMargin=&quot;0&quot; /&gt;
        ///  &lt;format name=&quot;A4248&quot;
        ///     PageTopMargin=&quot;12.5&quot;
        ///     PageRightMargin=&quot;7&quot;
        ///     PageBottomMargin=&quot;12.5&quot;
        ///     PageLeftMargin=&quot;7&quot;
        ///     PageHeight=&quot;297&quot;
        ///     PageWidth=&quot;210&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebControls_PrintLabel_labelFormatData {
            get {
                return ResourceManager.GetString("WebControls_PrintLabel_labelFormatData", resourceCulture);
            }
        }
    }
}
